{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alo7.android",
    "module": "asc-ext",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "gs4j56z5ubejpao4lthpx6yeve"
    }
  },
  "variants": [
    {
      "name": "noIflyEmbedReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "asc-ext-0.2.0-SNAPSHOT.aar",
          "url": "asc-ext-0.2.0-SNAPSHOT.aar",
          "size": 4071135,
          "sha512": "f74572c7e1486c076b2e60e12a00bc14b70979565e67afe249fd95492421ea96eec99f74460c4f6ad7b13dc4da03352f7b1d12d643565e84b5802092304b5997",
          "sha256": "a285aee5652f77b8276cce956f0ab2db8eef19f6c23e1c77d0625c3d6c702722",
          "sha1": "65c899489979d5f3540439d6d8018848159f4cc5",
          "md5": "f260f9bcbe23b10f08ecc16c759a258e"
        }
      ]
    },
    {
      "name": "noIflyEmbedReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.12"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.aliyun.sdk.android",
          "module": "AliyunPlayer",
          "version": {
            "requires": "4.7.4-full"
          }
        },
        {
          "group": "com.alivc.conan",
          "module": "AlivcConan",
          "version": {
            "requires": "0.9.5.1"
          }
        },
        {
          "group": "com.singsound.library",
          "module": "evaluating",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "asc-ext-0.2.0-SNAPSHOT.aar",
          "url": "asc-ext-0.2.0-SNAPSHOT.aar",
          "size": 4071135,
          "sha512": "f74572c7e1486c076b2e60e12a00bc14b70979565e67afe249fd95492421ea96eec99f74460c4f6ad7b13dc4da03352f7b1d12d643565e84b5802092304b5997",
          "sha256": "a285aee5652f77b8276cce956f0ab2db8eef19f6c23e1c77d0625c3d6c702722",
          "sha1": "65c899489979d5f3540439d6d8018848159f4cc5",
          "md5": "f260f9bcbe23b10f08ecc16c759a258e"
        }
      ]
    }
  ]
}
